-- =============================================================================
-- JËND PRO — Sales (Phase 9)
-- -----------------------------------------------------------------------------
-- * create_sale(): ONE transaction for number + lines + stock (SALE movements)
--   + payments (several methods) + credit part on the customer account.
--   Idempotent through client_reference (offline / retry safe).
-- * cancel_sale(): full cancellation — stock back (SALE_CANCELLATION), credit
--   reversed, refund as payment OUT. Sales are never edited or deleted.
-- * Prices always come from the catalog; reductions are explicit discounts
--   (sales.discount). Frozen unit costs live in sale_item_costs, readable only
--   with products.read_cost (cashiers never see margins).
-- See docs/business-rules.md §4.
-- =============================================================================

create type public.sale_status as enum ('COMPLETED', 'CANCELLED');

-- -----------------------------------------------------------------------------
-- sales
-- -----------------------------------------------------------------------------
create table public.sales (
  id               uuid primary key default gen_random_uuid(),
  business_id      uuid not null references public.businesses (id),
  number           text not null,
  -- Generated by the app for each sale; a retried request returns the same sale.
  client_reference uuid not null,
  location_id      uuid not null,
  customer_id      uuid,
  status           public.sale_status not null default 'COMPLETED',
  subtotal_amount  bigint not null check (subtotal_amount >= 0),
  discount_amount  bigint not null default 0 check (discount_amount >= 0),
  total_amount     bigint not null check (total_amount >= 0),
  -- Paid at checkout (sum of IN payments of the sale).
  amount_paid      bigint not null default 0 check (amount_paid >= 0),
  -- Left on the customer account.
  credit_amount    bigint not null default 0 check (credit_amount >= 0),
  payment_status   public.payment_status generated always as (private.payment_status(amount_paid, total_amount)) stored,
  notes            text check (char_length(notes) <= 500),
  sold_at          timestamptz not null default now(),
  sold_by          uuid default auth.uid() references auth.users (id) on delete set null,
  cancelled_at     timestamptz,
  cancelled_by     uuid references auth.users (id) on delete set null,
  cancel_reason    text check (char_length(cancel_reason) <= 500),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint sales_business_id_id_key unique (business_id, id),
  constraint sales_business_id_number_key unique (business_id, number),
  constraint sales_business_id_client_reference_key unique (business_id, client_reference),
  constraint sales_location_fkey foreign key (business_id, location_id)
    references public.locations (business_id, id),
  constraint sales_customer_fkey foreign key (business_id, customer_id)
    references public.customers (business_id, id),
  constraint sales_total_consistency_check check (total_amount = subtotal_amount - discount_amount),
  constraint sales_settlement_consistency_check check (amount_paid + credit_amount = total_amount),
  constraint sales_credit_customer_required_check check (credit_amount = 0 or customer_id is not null),
  constraint sales_cancelled_consistency_check check ((status = 'CANCELLED') = (cancelled_at is not null))
);

comment on table public.sales is 'Sales. Written only by create_sale() / cancel_sale().';

-- Sales journal, customer history, cashier's own sales.
create index sales_business_id_sold_at_idx on public.sales (business_id, sold_at desc);
create index sales_business_id_customer_id_idx on public.sales (business_id, customer_id) where customer_id is not null;
create index sales_business_id_sold_by_idx on public.sales (business_id, sold_by, sold_at desc);

create trigger set_updated_at
  before update on public.sales
  for each row execute function private.set_updated_at();

-- -----------------------------------------------------------------------------
-- sale_items / sale_item_costs
-- -----------------------------------------------------------------------------
create table public.sale_items (
  id              uuid primary key default gen_random_uuid(),
  business_id     uuid not null,
  sale_id         uuid not null,
  product_id      uuid not null,
  -- Frozen at sale time: later catalog changes never rewrite history.
  product_name    text not null,
  quantity        numeric(14, 3) not null check (quantity > 0),
  unit_price      bigint not null check (unit_price >= 0),
  discount_amount bigint not null default 0 check (discount_amount >= 0),
  line_total      bigint not null check (line_total >= 0),
  created_at      timestamptz not null default now(),
  constraint sale_items_business_id_id_key unique (business_id, id),
  constraint sale_items_sale_fkey foreign key (business_id, sale_id)
    references public.sales (business_id, id),
  constraint sale_items_product_fkey foreign key (business_id, product_id)
    references public.products (business_id, id),
  constraint sale_items_sale_product_key unique (sale_id, product_id)
);

-- Lines of a sale (FK join) and best-sellers per product.
create index sale_items_business_sale_idx on public.sale_items (business_id, sale_id);
create index sale_items_business_product_idx on public.sale_items (business_id, product_id);

create table public.sale_item_costs (
  sale_item_id uuid primary key,
  business_id  uuid not null,
  -- Unit cost frozen at sale time (margin computation).
  unit_cost    bigint not null check (unit_cost >= 0),
  constraint sale_item_costs_item_fkey foreign key (business_id, sale_item_id)
    references public.sale_items (business_id, id)
);

comment on table public.sale_item_costs is
  'Frozen unit cost per sale line, readable only with products.read_cost.';

-- -----------------------------------------------------------------------------
-- payments and customer ledger: sale context
-- -----------------------------------------------------------------------------
alter table public.payments
  add column sale_id uuid,
  add constraint payments_sale_fkey foreign key (business_id, sale_id)
    references public.sales (business_id, id),
  drop constraint payments_context_check,
  add constraint payments_context_check check (num_nonnulls(customer_id, purchase_id, sale_id) = 1);

create index payments_business_id_sale_id_idx on public.payments (business_id, sale_id) where sale_id is not null;

alter table public.customer_transactions
  add column sale_id uuid,
  add constraint customer_transactions_sale_fkey foreign key (business_id, sale_id)
    references public.sales (business_id, id),
  add constraint customer_transactions_sale_required_check
    check ((type in ('CREDIT_SALE', 'SALE_CANCELLATION')) = (sale_id is not null));

-- Account engine gains the sale link (signature change => drop + create).
drop function private.apply_customer_transaction(uuid, uuid, public.customer_transaction_type, bigint, uuid, text);

create function private.apply_customer_transaction(
  p_business_id uuid,
  p_customer_id uuid,
  p_type        public.customer_transaction_type,
  p_amount      bigint,
  p_payment_id  uuid default null,
  p_note        text default null,
  p_sale_id     uuid default null
)
returns public.customer_transactions
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_customer public.customers;
  v_after    bigint;
  v_tx       public.customer_transactions;
begin
  if p_amount is null or p_amount = 0 then
    raise exception 'INVALID_AMOUNT' using errcode = '22023';
  end if;

  select * into v_customer from public.customers
   where business_id = p_business_id and id = p_customer_id
   for update;
  if not found then
    raise exception 'CUSTOMER_NOT_FOUND' using errcode = 'P0002';
  end if;

  v_after := v_customer.balance + p_amount;
  if v_after < 0 then
    raise exception 'AMOUNT_EXCEEDS_BALANCE' using errcode = 'P0001',
      detail = json_build_object('balance', v_customer.balance, 'requested', -p_amount)::text;
  end if;
  if p_type = 'CREDIT_SALE' then
    if v_customer.status <> 'ACTIVE' then
      raise exception 'CUSTOMER_ARCHIVED' using errcode = 'P0001';
    end if;
    if v_customer.credit_limit is not null and v_after > v_customer.credit_limit then
      raise exception 'CREDIT_LIMIT_EXCEEDED' using errcode = 'P0001',
        detail = json_build_object('balance', v_customer.balance, 'credit_limit', v_customer.credit_limit,
                                   'requested', p_amount)::text;
    end if;
  end if;

  update public.customers set balance = v_after where id = p_customer_id;

  insert into public.customer_transactions (business_id, customer_id, type, amount, balance_after,
                                            payment_id, sale_id, note)
  values (p_business_id, p_customer_id, p_type, p_amount, v_after, p_payment_id, p_sale_id,
          nullif(btrim(p_note), ''))
  returning * into v_tx;
  return v_tx;
end;
$$;

create index customer_transactions_business_sale_idx on public.customer_transactions (business_id, sale_id)
  where sale_id is not null;

-- -----------------------------------------------------------------------------
-- create_sale
-- p_items:    [{"product_id": uuid, "quantity": number, "discount_amount"?: integer}, …]
-- p_payments: [{"method": "CASH"|"WAVE"|…, "amount": integer, "external_reference"?: text}, …]
-- Unpaid remainder = credit (requires sales.credit and a customer).
-- -----------------------------------------------------------------------------
create or replace function public.create_sale(
  p_business_id      uuid,
  p_client_reference uuid,
  p_location_id      uuid,
  p_items            jsonb,
  p_payments         jsonb default '[]'::jsonb,
  p_customer_id      uuid default null,
  p_discount_amount  bigint default 0,
  p_notes            text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_sale_id      uuid;
  v_item         jsonb;
  v_payment      jsonb;
  v_product      public.products;
  v_product_id   uuid;
  v_quantity     numeric(14, 3);
  v_line_disc    bigint;
  v_method       public.payment_method;
  v_pay_amount   bigint;
  v_subtotal     bigint := 0;
  v_discount     bigint := coalesce(p_discount_amount, 0);
  v_has_discount boolean := coalesce(p_discount_amount, 0) > 0;
  v_paid         bigint := 0;
  v_total        bigint;
  v_credit       bigint;
  v_line         record;
  v_item_id      uuid;
  v_lines        jsonb := '[]'::jsonb;
begin
  perform private.require_permission(p_business_id, 'sales.create');

  if p_client_reference is null then
    raise exception 'CLIENT_REFERENCE_REQUIRED' using errcode = '22023';
  end if;
  -- Idempotency: a retried request returns the original sale.
  select id into v_sale_id from public.sales
   where business_id = p_business_id and client_reference = p_client_reference;
  if found then
    return v_sale_id;
  end if;

  if not exists (select 1 from public.locations
                  where business_id = p_business_id and id = p_location_id and status = 'ACTIVE') then
    raise exception 'LOCATION_NOT_FOUND' using errcode = 'P0002';
  end if;
  if p_customer_id is not null and not exists (
    select 1 from public.customers where business_id = p_business_id and id = p_customer_id and status = 'ACTIVE') then
    raise exception 'CUSTOMER_NOT_FOUND' using errcode = 'P0002';
  end if;
  if v_discount < 0 then
    raise exception 'INVALID_AMOUNT' using errcode = '22023';
  end if;

  -- ---- Lines: validate, price from catalog, compute -------------------------
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'ITEMS_REQUIRED' using errcode = '22023';
  end if;

  for v_item in select * from jsonb_array_elements(p_items) loop
    begin
      v_product_id := (v_item ->> 'product_id')::uuid;
      v_quantity   := (v_item ->> 'quantity')::numeric;
      v_line_disc  := coalesce((v_item ->> 'discount_amount')::bigint, 0);
    exception when others then
      raise exception 'INVALID_ITEM' using errcode = '22023', detail = v_item::text;
    end;
    if v_quantity is null or v_quantity <= 0 or v_line_disc < 0 then
      raise exception 'INVALID_ITEM' using errcode = '22023', detail = v_item::text;
    end if;

    select * into v_product from public.products where business_id = p_business_id and id = v_product_id;
    if not found then
      raise exception 'PRODUCT_NOT_FOUND' using errcode = 'P0002', detail = v_product_id::text;
    end if;
    if v_product.status <> 'ACTIVE' then
      raise exception 'PRODUCT_ARCHIVED' using errcode = 'P0001', detail = v_product_id::text;
    end if;
    if not v_product.allows_fractional_quantity and v_quantity <> trunc(v_quantity) then
      raise exception 'FRACTIONAL_QUANTITY_NOT_ALLOWED' using errcode = 'P0001', detail = v_product_id::text;
    end if;
    if v_line_disc > round(v_quantity * v_product.sale_price) then
      raise exception 'DISCOUNT_EXCEEDS_TOTAL' using errcode = '22023', detail = v_product_id::text;
    end if;
    if v_lines @> jsonb_build_array(jsonb_build_object('product_id', v_product_id)) then
      raise exception 'DUPLICATE_PRODUCT' using errcode = '22023', detail = v_product_id::text;
    end if;

    v_has_discount := v_has_discount or v_line_disc > 0;
    v_lines := v_lines || jsonb_build_array(jsonb_build_object(
      'product_id', v_product_id,
      'product_name', v_product.name,
      'track_stock', v_product.track_stock,
      'quantity', v_quantity,
      'unit_price', v_product.sale_price,
      'discount_amount', v_line_disc,
      'line_total', round(v_quantity * v_product.sale_price)::bigint - v_line_disc));
    v_subtotal := v_subtotal + round(v_quantity * v_product.sale_price)::bigint - v_line_disc;
  end loop;

  if v_has_discount then
    perform private.require_permission(p_business_id, 'sales.discount');
  end if;
  if v_discount > v_subtotal then
    raise exception 'DISCOUNT_EXCEEDS_TOTAL' using errcode = '22023';
  end if;
  v_total := v_subtotal - v_discount;

  -- ---- Payments: validate and sum ------------------------------------------
  if p_payments is null or jsonb_typeof(p_payments) <> 'array' then
    raise exception 'INVALID_PAYMENT' using errcode = '22023';
  end if;
  for v_payment in select * from jsonb_array_elements(p_payments) loop
    begin
      v_method     := (v_payment ->> 'method')::public.payment_method;
      v_pay_amount := (v_payment ->> 'amount')::bigint;
    exception when others then
      raise exception 'INVALID_PAYMENT' using errcode = '22023', detail = v_payment::text;
    end;
    if v_method is null or v_pay_amount is null or v_pay_amount <= 0 then
      raise exception 'INVALID_PAYMENT' using errcode = '22023', detail = v_payment::text;
    end if;
    v_paid := v_paid + v_pay_amount;
  end loop;
  if v_paid > v_total then
    -- Change given back is not a payment: send only the amount due.
    raise exception 'PAYMENT_EXCEEDS_TOTAL' using errcode = '22023',
      detail = json_build_object('total', v_total, 'paid', v_paid)::text;
  end if;

  v_credit := v_total - v_paid;
  if v_credit > 0 then
    perform private.require_permission(p_business_id, 'sales.credit');
    if p_customer_id is null then
      raise exception 'CUSTOMER_REQUIRED_FOR_CREDIT' using errcode = 'P0001';
    end if;
  end if;

  -- ---- Write ----------------------------------------------------------------
  begin
    insert into public.sales (business_id, number, client_reference, location_id, customer_id,
                              subtotal_amount, discount_amount, total_amount, amount_paid, credit_amount, notes)
    values (p_business_id, private.next_document_number(p_business_id, 'SALE'), p_client_reference,
            p_location_id, p_customer_id, v_subtotal, v_discount, v_total, v_paid, v_credit,
            nullif(btrim(p_notes), ''))
    returning id into v_sale_id;
  exception when unique_violation then
    -- Concurrent retry of the same sale committed first.
    select id into v_sale_id from public.sales
     where business_id = p_business_id and client_reference = p_client_reference;
    if v_sale_id is null then
      raise;
    end if;
    return v_sale_id;
  end;

  -- Lines and stock, in product order (deterministic locking).
  for v_line in
    select * from jsonb_to_recordset(v_lines) as x(
      product_id uuid, product_name text, track_stock boolean, quantity numeric,
      unit_price bigint, discount_amount bigint, line_total bigint)
    order by product_id
  loop
    insert into public.sale_items (business_id, sale_id, product_id, product_name, quantity,
                                   unit_price, discount_amount, line_total)
    values (p_business_id, v_sale_id, v_line.product_id, v_line.product_name, v_line.quantity,
            v_line.unit_price, v_line.discount_amount, v_line.line_total)
    returning id into v_item_id;

    insert into public.sale_item_costs (sale_item_id, business_id, unit_cost)
    values (v_item_id, p_business_id, private.current_unit_cost(v_line.product_id));

    if v_line.track_stock then
      perform private.apply_stock_movement(p_business_id, v_line.product_id, p_location_id, 'SALE',
        -v_line.quantity, private.current_unit_cost(v_line.product_id), 'sale', v_sale_id, null, null);
    end if;
  end loop;

  for v_payment in select * from jsonb_array_elements(p_payments) loop
    insert into public.payments (business_id, location_id, direction, method, amount, sale_id, external_reference)
    values (p_business_id, p_location_id, 'IN', (v_payment ->> 'method')::public.payment_method,
            (v_payment ->> 'amount')::bigint, v_sale_id, nullif(btrim(v_payment ->> 'external_reference'), ''));
  end loop;

  if v_credit > 0 then
    perform private.apply_customer_transaction(p_business_id, p_customer_id, 'CREDIT_SALE', v_credit,
                                               null, null, v_sale_id);
  end if;

  if v_has_discount then
    perform private.log_audit(p_business_id, 'sale.discount', 'sale', v_sale_id,
      jsonb_build_object('subtotal_before_discounts', v_subtotal + (select coalesce(sum((l ->> 'discount_amount')::bigint), 0)
                                                                     from jsonb_array_elements(v_lines) l),
                         'line_discounts', (select coalesce(sum((l ->> 'discount_amount')::bigint), 0)
                                              from jsonb_array_elements(v_lines) l),
                         'sale_discount', v_discount, 'total', v_total));
  end if;

  return v_sale_id;
end;
$$;

-- -----------------------------------------------------------------------------
-- cancel_sale — full cancellation
-- Credit is reversed up to the customer's current balance; whatever the customer
-- has already settled on that credit, plus the amount paid at checkout, is
-- refunded (payment OUT). Stock goes back to the sale location.
-- -----------------------------------------------------------------------------
create or replace function public.cancel_sale(
  p_sale_id       uuid,
  p_reason        text,
  p_refund_method public.payment_method default 'CASH'
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_sale     public.sales;
  v_line     record;
  v_balance  bigint;
  v_reversed bigint := 0;
  v_refund   bigint;
begin
  select * into v_sale from public.sales where id = p_sale_id for update;
  perform private.require_permission(v_sale.business_id, 'sales.cancel');
  if v_sale.status <> 'COMPLETED' then
    raise exception 'SALE_ALREADY_CANCELLED' using errcode = 'P0001';
  end if;
  if coalesce(btrim(p_reason), '') = '' then
    raise exception 'REASON_REQUIRED' using errcode = '22023';
  end if;

  -- Stock back, product order.
  for v_line in
    select si.product_id, si.quantity, p.track_stock
      from public.sale_items si
      join public.products p on p.business_id = si.business_id and p.id = si.product_id
     where si.sale_id = p_sale_id
     order by si.product_id
  loop
    if v_line.track_stock then
      perform private.apply_stock_movement(v_sale.business_id, v_line.product_id, v_sale.location_id,
        'SALE_CANCELLATION', v_line.quantity, private.current_unit_cost(v_line.product_id),
        'sale', p_sale_id, null, p_reason);
    end if;
  end loop;

  -- Credit part.
  if v_sale.credit_amount > 0 then
    select balance into v_balance from public.customers where id = v_sale.customer_id for update;
    v_reversed := least(v_sale.credit_amount, v_balance);
    if v_reversed > 0 then
      perform private.apply_customer_transaction(v_sale.business_id, v_sale.customer_id, 'SALE_CANCELLATION',
                                                 -v_reversed, null, p_reason, p_sale_id);
    end if;
  end if;

  -- Refund what the customer actually paid.
  v_refund := v_sale.amount_paid + (v_sale.credit_amount - v_reversed);
  if v_refund > 0 then
    insert into public.payments (business_id, location_id, direction, method, amount, sale_id, note)
    values (v_sale.business_id, v_sale.location_id, 'OUT', p_refund_method, v_refund, p_sale_id,
            'Remboursement annulation ' || v_sale.number);
  end if;

  update public.sales
     set status = 'CANCELLED', cancelled_at = now(), cancelled_by = (select auth.uid()),
         cancel_reason = btrim(p_reason)
   where id = p_sale_id;

  perform private.log_audit(v_sale.business_id, 'sale.cancel', 'sale', p_sale_id,
    jsonb_build_object('number', v_sale.number, 'total', v_sale.total_amount, 'refund', v_refund,
                       'credit_reversed', v_reversed, 'reason', btrim(p_reason)));
end;
$$;

-- -----------------------------------------------------------------------------
-- Privileges + RLS: read-only for clients.
-- -----------------------------------------------------------------------------
alter table public.sales           enable row level security;
alter table public.sale_items      enable row level security;
alter table public.sale_item_costs enable row level security;

grant select on public.sales, public.sale_items, public.sale_item_costs to authenticated;

create policy "members with sales.read can select sales"
  on public.sales for select to authenticated
  using (business_id in (select private.businesses_with_permission('sales.read')));

create policy "members with sales.read_own can select their own sales"
  on public.sales for select to authenticated
  using (sold_by = (select auth.uid())
         and business_id in (select private.businesses_with_permission('sales.read_own')));

-- Lines follow the visibility of their sale (sales RLS applies in the subquery).
create policy "members can select lines of visible sales"
  on public.sale_items for select to authenticated
  using (exists (select 1 from public.sales s where s.business_id = sale_items.business_id and s.id = sale_items.sale_id));

create policy "members with products.read_cost can select sale costs"
  on public.sale_item_costs for select to authenticated
  using (business_id in (select private.businesses_with_permission('products.read_cost'))
         and business_id in (select private.businesses_with_permission('sales.read')));

create policy "members can select payments of visible sales"
  on public.payments for select to authenticated
  using (sale_id is not null
         and exists (select 1 from public.sales s where s.business_id = payments.business_id and s.id = payments.sale_id));

revoke all on function
  public.create_sale(uuid, uuid, uuid, jsonb, jsonb, uuid, bigint, text),
  public.cancel_sale(uuid, text, public.payment_method)
from public, anon;

grant execute on function
  public.create_sale(uuid, uuid, uuid, jsonb, jsonb, uuid, bigint, text),
  public.cancel_sale(uuid, text, public.payment_method)
to authenticated;
